spring.application.name=apiGateway

server.port=${PORT:8080}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

logging.level.org.springframework.cloud.gateway=DEBUG

eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.non-secure-port-enabled=false