spring.application.name=apiGateway

server.port=8765

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.org.springframework.cloud.gateway=DEBUG

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}